### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by LcenArthas** [shadyabh/Correction-Filter#1]
Hello, I use blind to run, this error occurs, can you help me

**Comment by shadyabh** [comment]
Did you modify the code? Which SR model did you use?

**Comment by LcenArthas** [comment]
I didn't change the core code, I just hooked it up to the back end of the RCAN output. R_dag in the code I use my RCAN model output

**Comment by shadyabh** [comment]
Please note that you need to define the SR network such that it allows the gradients of the input to propagate through it. Try to define your SR model similarly to what is written in the code (we used DBPN).
