### ISSUE TITLE
Artefacts with ERSGAN for blind correction

### ISSUE THREAD

**Issue by claroche-gpfw-zz** [shadyabh/Correction-Filter#2]
Hi,

Thanks for the code, very interesting way of seeing the generalization problem in SR. I tried to applied the blind correction with pre-trained x4 ESRGAN from https://github.com/cszn/KAIR. The results contain a lot of artefacts (I use 250 iterations but it becomes worst if I increase the number of iterations).
![Fail_kern_corr](https://user-images.githubusercontent.com/65959416/85402525-1e686c00-b55c-11ea-8333-7ad63c1a1df1.png)
Did you also tried with ESRGAN and faced the same issue ?

Also, the number of iterations and step size are not the same in the paper and in the code. Should I use the one from the paper or the one from the code ?

Thanks !

**Comment by shadyabh** [comment]
Hi,

Please note that our method assumes SR models that are not based on GANs, we need to match the LR image, not to create new details.

Regarding the code, we changed it a bit, we will add a version that gives the results stated in the article in the future. The current version gives similar results (sometimes even better).

Thanks
