### ISSUE TITLE
Some blind correct-filter results seem to be strange 

### ISSUE THREAD

**Issue by guangpintao** [shadyabh/Correction-Filter#4]
NICE WORK! But i've got some problems when use the blind SR experiment setting, DIV2K_valid is used as input after Gaussian kernel blur with variance of 3 and downsampled with scale factor 4. I choose RCAN as the SR network, some of the image obtained by correct filter are as shown below:
![0801_x4_corr_est](https://user-images.githubusercontent.com/32570671/89659607-acc56100-d902-11ea-8f4d-fb9cc84be8fe.png)
![0802_x4_corr_est](https://user-images.githubusercontent.com/32570671/89659637-b9e25000-d902-11ea-97ac-24e4b413b434.png)
![0803_x4_corr_est](https://user-images.githubusercontent.com/32570671/89659643-bbac1380-d902-11ea-97b1-2dd26ee97701.png)
![0804_x4_corr_est](https://user-images.githubusercontent.com/32570671/89659676-c666a880-d902-11ea-91cd-d8edc0ed2198.png)
![0805_x4_corr_est](https://user-images.githubusercontent.com/32570671/89659719-d5e5f180-d902-11ea-8d2a-eefe81a179a4.png)
There may be some problems with my experimental settings. Please give me some advice.I'm not sure whether these input lr can get good SR result.

**Comment by shadyabh** [comment]
Hi,

Thanks for your interest, I checked the scenario you mentioned with DBPN iterative, which is what we worked with for the blind case in the article and the results were as expected, see here
- LR Gaussian with std 3.0 blurred image
![test_std3](https://user-images.githubusercontent.com/58180706/89708585-fb591680-d967-11ea-8533-257342905809.png)
- LR Corrected image
![test_std3_x4_corr_est](https://user-images.githubusercontent.com/58180706/89708593-0b70f600-d968-11ea-92c2-2bc96cce64fb.png)

Maybe there was a problem with the integration of RCAN code? or that you blurred the images without centralizing the kernels to the sampling grid (common issue)?

**Comment by RohanKPatil** [comment]
I am facing the same issue. I am using original images (without downsampling) with RCAN and the corrected images look strange just like the ones posted by @Gptao . During correction, the loss is also more as compared to that for DBPN_Iterative. For the same setup, replacing the RCAN model with DBPN_Iterative gives good corrected images. Did you test the blind setting with RCAN for any test case?
![bird_x2_corrected_est](https://user-images.githubusercontent.com/14365080/128065541-d106d9c9-099c-456d-ac6c-c64a51aaadbd.png)

**Comment by shadyabh** [comment]
Hi @RohanKPatil, 

Thank you for your interest. 

We have not tested the blind algorithm with RCAN, I assume that it needs some hyper-parameters tuning (e.g. per_std, lambda_l0, crop size, padding type).

Also it seems like the estimated kernel is not centered, which can be solved by adding a regularization term using the function https://github.com/shadyabh/Correction-Filter/blob/9d7ca79281aa9a621a5bd2cc5e4880adfc8696c5/utils.py#L173 which indicates how much the kernel is centered.

I hope this helps you.
