### ISSUE TITLE
How to use correct_img.py and estimate_correction.py?

### ISSUE THREAD

**Issue by yanghedada** [shadyabh/Correction-Filter#5]
### How to use correct_img.py and estimate_correction.py?

Hello, is the input and output of correct_img.py an HR image or an LR image？

**Comment by shadyabh** [comment]
Hi, 
The input for them is the LR image, you need to perform the downsampling externally. 
We have "downsample_using_h" in utils.py that performs the downsampling using given kernel and scale factor.
