### ISSUE TITLE
PSNR results

### ISSUE THREAD

**Issue by FuzhiYang** [shadyabh/Correction-Filter#6]
When I evaluated PSNR on Set14 dataset. I blured the image with 32x32 gaussian blur kernel with sigma 2.5/sqrt(2), and then I used matlab's bicubic imresize function to x2 downsample it like below:
![comic](https://user-images.githubusercontent.com/11538235/90646658-09f9d480-e26a-11ea-87d8-ca5a5219bd33.png)

Then I ran "correct_imgs.py" to get the corrected results like this:
![comic_x2_corr_corrected](https://user-images.githubusercontent.com/11538235/90646715-1847f080-e26a-11ea-89ee-3ee36c10534d.png)

Finally I forward this corrected image to RCAN_x2 model and got this:
![comic_x2_corr_corrected](https://user-images.githubusercontent.com/11538235/90646836-3b72a000-e26a-11ea-8574-9deced7594af.png)

But the PSNR on Set14 is only about 24, which is far lower than the reported number in the paper, 31.272. Did I make some mistakes during these steps? Could you share the details of your degradation process? (gaussian blur, bicubic downsample, etc)

**Comment by shadyabh** [comment]
This is the wrong way to downsample an image, you need to blur then subsample not blur then bicubic downsample.
First, you apply 32x32 Gaussian then you will need to subsample it directly or work with a stride in your convolution. 
Please check "downsample_using_h" in utils.py.

Good luck
