### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by crenaudineau1** [shadyabh/Correction-Filter#7]
Hello,

Could you add your pretrained models with your correction (ie. ProSR with our correction, RCAN with our correction, DBPN with our correction) on the github with a Google Drive link ? 

Thank you very much.

**Comment by shadyabh** [comment]
Hi, 

Please note that we don't train any network, we plug the LR image into the correction filter before applying the trained SR model. There is no training needed so you may use the weights from the original articles.

Good luck!
