### ISSUE TITLE
Test question

### ISSUE THREAD

**Issue by crisfan927** [shadyabh/Correction-Filter#8]
Hello,author
Did the input file of 'correct_imgs.py 'put the images sampled under Bicubic?
Does the input file 'estimate_correction. Py' place the busy sampled image?

Thank you !

**Comment by shadyabh** [comment]
Hi, 

Thank you for you interest.
Regarding your first question, "correct_imgs.py" takes an input dir with the LR images, you will also need to give it the target and source sampling kernels (in the code it is configured to bicubic and Gaussian respectivly), then it will output the corrected LR images to the output directory that you also need to configure.

Regarding your second question, I am not sure I understand it properly, the "estimate_correction.py" takes only the LR images and the target sampling kernel (usually bicubic), then it will estimate the correction filter without knowing the source sampling kernel.

Note that in the code source = Gaussian, target = bicubic.

Good luck,
Shady
